name: Auto Version Tag

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get the current version tag
        id: get_tag
        run: |
          VERSION=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$VERSION" ]; then VERSION="v0.0.0"; fi
          echo "current_version=${VERSION}" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          MAJOR_MINOR_PATCH=(${current_version//./ })
          PATCH=$((MAJOR_MINOR_PATCH[2] + 1))
          NEW_VERSION="${MAJOR_MINOR_PATCH[0]}.${MAJOR_MINOR_PATCH[1]}.$PATCH"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
